writeable_parameters:

  ### INPUT CHANNELS SETUP ###
  # Should not need to change, just make sure you connect the spectroscopy device to CH1
  dual_channel:
    hardware_name: dual_channel
    initial_value: false # True if you want to use dual channel mode, ie mix CH1 and CH2, False if you want to use only CH1
    scaling: null # scaling must be None for True/False parameters
  
  channel_mixing:
    hardware_name: channel_mixing
    initial_value: -128 # goes from -128 to +128, -128 means only CH1, 128 means only CH2, 0 means equal mixing of both channels
    scaling: null

  # Should not need to change
  # Now I set the CH1 input to have no offset correction, no signal inversion, and two low-pass filters
  demodulation_multiplier_a:
    hardware_name: demodulation_multiplier_a
    initial_value: 1.0 # This is the multiplier for the demodulation signal, 1.0 looking for modulation frequency
    scaling: 1.0

  offset_a:
    hardware_name: offset_a
    initial_value: 0.005 # This is the offset for the CH1 input, 0.0 means no offset correction
    scaling: 8191.0

  invert_a:
    hardware_name: invert_a
    initial_value: False # True if you want to invert the CH1 input signal, False otherwise
    scaling: null

  filter_automatic_a:
    hardware_name: filter_automatic_a
    initial_value: False # True if you want to use the automatic filter, False otherwise
    scaling: null

  filter_1_enabled_a:
    hardware_name: filter_1_enabled_a
    initial_value: True # True if you want to use the first low-pass filter, False otherwise
    scaling: null
  
  filter_1_type_a:
    hardware_name: filter_1_type_a
    initial_value: 0 # 0 for Low-pass, 1 for High-pass
    scaling: 1.0

  filter_2_enabled_a:
    hardware_name: filter_2_enabled_a
    initial_value: True # True if you want to use the second low-pass filter, False otherwise
    scaling: null 

  filter_2_type_a:
    hardware_name: filter_2_type_a
    initial_value: 0 # 0 for Low-pass, 1 for High-pass
    scaling: 1.0

  # Should not need to change
  # Now I set the CH2 input to have no offset correction, no signal inversion, and two low-pass filters
  demodulation_multiplier_b:
    hardware_name: demodulation_multiplier_b
    initial_value: 1.0 # This is the multiplier for the demodulation signal
    scaling: 1.0

  offset_b:
    hardware_name: offset_b
    initial_value: 0.0 # This is the offset for the CH2 input,
    scaling: 1.0
  
  invert_b:
    hardware_name: invert_b
    initial_value: False # True if you want to invert the CH2 input signal, False
    scaling: null

  filter_automatic_b:
    hardware_name: filter_automatic_b
    initial_value: False # True if you want to use the automatic filter, False otherwise
    scaling: null

  filter_1_enabled_b:
    hardware_name: filter_1_enabled_b
    initial_value: True # True if you want to use the first low-pass filter, False
    scaling: null

  filter_1_type_b:
    hardware_name: filter_1_type_b
    initial_value: 0 # 0 for Low-pass, 1 for High-pass
    scaling: 1.0
  
  filter_2_enabled_b:
    hardware_name: filter_2_enabled_b
    initial_value: True # True if you want to use the second low-pass filter, False
    scaling: null

  filter_2_type_b:
    hardware_name: filter_2_type_b
    initial_value: 0 # 0 for Low-pass, 1 for High-pass
    scaling: 1.0


  ### OUTPUT CHANNELS SETUP ###
  # These are the analog_outs you physically connect from your device to the actual setup
  big_offset:
    hardware_name: analog_out_1
    initial_value: 0.93
    scaling: 18204. # This is approx 1.0 / ANALOG_OUT_V

  small_offset:
    hardware_name: analog_out_2
    initial_value: 0.
    scaling: 18204. # This is approx 1.0 / ANALOG_OUT_V

  modulation_channel:
    hardware_name: mod_channel
    initial_value: 0 # 0 for CH1, 1 for CH2, 2 for ANALOG_OUT_0
    scaling: null # scaling must be None for channel selection parameters  

  sweep_channel:
    hardware_name: sweep_channel
    initial_value: 1 # 0 for CH1, 1 for CH2, 2 for ANALOG_OUT_0
    scaling: null

  control_channel:
    hardware_name: control_channel
    initial_value: 1 # 0 for CH1, 1 for CH2, 2 for ANALOG_OUT_0
    scaling: null

  polarity_fast_out1:
    hardware_name: polarity_fast_out1
    initial_value: 0 # 0 if when signal increases laser frequency increases, 1 if it decreases (NB absolute value not true, important is relative value to slow output)
    scaling: null # scaling must be None for Option Parameters
  
  polarity_fast_out2:
    hardware_name: polarity_fast_out2
    initial_value: 0 # 0 if when signal increases laser frequency increases, 1 if it decreases (NB absolute value not true, important is relative value to slow output)
    scaling: null

  slow_control_channel:
    hardware_name: slow_control_channel
    initial_value: 2 # 0 for CH1, 1 for CH2, 2 for ANALOG_OUT_0
    scaling: null

  polarity_analog_out0:
    hardware_name: polarity_analog_out0
    initial_value: 1 # 0 if when signal increases laser frequency increases, 1 if it decreases (NB absolute value not true, important is relative value to slow output)
    scaling: null

  
  ### MODULATION SETUP ###
  # These parameters control the modulation of the laser frequency
  modulation_amplitude:
    hardware_name: modulation_amplitude
    initial_value: 1.8
    scaling: 4095.75  # This is value of Vpp constant

  modulation_frequency:
    hardware_name: modulation_frequency
    initial_value: 0.05
    scaling: 33554432.0 # This is the value of MHz constant

  ### SWEEP SETUP ###
  sweep_amplitude:
    hardware_name: sweep_amplitude
    initial_value: 0.9 # This is the amplitude of the sweep signal as a percentage of the maximum output voltage of the sweep channel
    scaling: 1.0

  sweep_center:
    hardware_name: sweep_center
    initial_value: 0.0 # center the sweep on the 0V of the channel
    scaling: 1.0

  sweep_speed:
    hardware_name: sweep_speed
    initial_value: 8 # n means (3.8 kHz / 2**n), eg n=12 means 0.92 Hz
    scaling: null


  ### SIGNAL PROCESSING SETUP ###
  # These parameters control the signal processing of the spectroscopy signal, namely the demolutaion phase and filters
  phase:
    hardware_name: demodulation_phase_a
    initial_value: 150
    scaling: 1.0  # degrees

  filter_1_frequency:
    hardware_name: filter_1_frequency_a
    initial_value: 10000
    scaling: 1.0  # Hz

  filter_2_frequency:
    hardware_name: filter_2_frequency_a
    initial_value: 10000
    scaling: 1.0  # Hz

  ### PID CONTROL SETUP ###
  pid_p:
    hardware_name: p
    initial_value: 5000
    scaling: 1.0  # PID proportional gain

  pid_i:
    hardware_name: i
    initial_value: 100
    scaling: 1.0  # PID integral gain

  pid_d:
    hardware_name: d
    initial_value: 0
    scaling: 1.0  # PID derivative gain

  pid_on_slow_enabled:
    hardware_name: pid_on_slow_enabled
    initial_value: True  # True if PID control on slow channel is enabled, False otherwise
    scaling: null

  pid_slow_strength:
    hardware_name: pid_on_slow_strength
    initial_value: 1000
    scaling: 1.0  # PID strength on slow control

  ### SIGNAL HISTORY SETUP ###
  # Should not need to change
  control_history_length:
    hardware_name: control_signal_history_length
    initial_value: 1000 # Length of control signal history buffer in seconds
    scaling: 1.0  # Control signal history buffer size

readable_parameters:
  sweep_signal:
    hardware_name: to_plot

  control_signal_history:
    hardware_name: control_signal_history
  
  monitor_signal_history:
    hardware_name: monitor_signal_history
