# Linien hardware configuration
devices:
  - name: local_host
    ip: 192.168.1.159
    linien_port: 18862
    ssh_port: 22
  - name: vpn_host
    ip: 10.194.33.151
    linien_port: 2224
    ssh_port: 2223
username: root              # Login user
password: root              # Login password